name: React.js Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm i
        working-directory: "./frontend"

      - name: Run tests
        run: npm test --if-present -- --passWithNoTests
        working-directory: "./frontend"

      - name: Build application
        run: npm run build --if-present
        working-directory: "./frontend"

#       - name: Compress files
#         run: |
#           zip -r artifact.zip .

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v2
#         with:
#           name: node-app
#           path: artifact.zip
       

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v2
#       with:
#         name: node-app

#     - name: 'Deploy to Azure Web App'
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'IFRC-GO-Make-Maps-Frontend'
#         slot-name: 'Production'
#         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C7781ABE22564DF89122B66B303E79F3 }}
#         package: .

